### ISSUE TITLE
Provide advice on integrating flask-db with Flask-Migrate

### ISSUE THREAD

**Issue by jerrydboonstra** [nickjj/flask-db#10]
I've switched back and forth between these libraries, but I could only get Flask-Migrate working in my multi-database environment.  I miss the ability to use 'flask db seed' though.  Why can't these libraries co-exist?  Of course there is the namespace collision on "flask db" but can't there be a workaround provided?

**Comment by nickjj** [comment]
Hi,

I haven't used a multi-DB environment yet but if it's something Alembic supports it should mostly work with this extension since all this extension does is generate Alembic config files and run Alembic commands. Maybe a PR could be made here to potentially support initializing a multi-db project if the initial config files end up being drastically different? What do your Alembic related config files look like to support multiple databases?

I'm not sure how to integrate both extensions together. If both extensions register a command with the same name there's going to be a conflict. The `db` command itself (as a name) is defined in the `setup.py` file which as far as I know means it's not something that can be configured at the extension level since this gets loaded before the extension's config options are loaded. I could be wrong here tho.

**Comment by nickjj** [comment]
Going to close this as there's not much that can be done here other than change the entire name of this package.
